// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz8QsfGuR3EDB8rElpuSIWuJNSJ24gFro',
    appId: '1:303663460854:web:4d6a8b79f61e6adef597d7',
    messagingSenderId: '303663460854',
    projectId: 'calorie-calculator-app-2025',
    authDomain: 'calorie-calculator-app-2025.firebaseapp.com',
    storageBucket: 'calorie-calculator-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAd4D1q9FsiJCzmlK8560NDCsRvXWUCrY',
    appId: '1:303663460854:android:a308015aec3a3f13f597d7',
    messagingSenderId: '303663460854',
    projectId: 'calorie-calculator-app-2025',
    storageBucket: 'calorie-calculator-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmR-pjN7Gu4MNYGepqeBH5dCP_xs2Y1E',
    appId: '1:303663460854:ios:7e15d140b4019dbcf597d7',
    messagingSenderId: '303663460854',
    projectId: 'calorie-calculator-app-2025',
    storageBucket: 'calorie-calculator-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.calorieCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnmR-pjN7Gu4MNYGepqeBH5dCP_xs2Y1E',
    appId: '1:303663460854:ios:7e15d140b4019dbcf597d7',
    messagingSenderId: '303663460854',
    projectId: 'calorie-calculator-app-2025',
    storageBucket: 'calorie-calculator-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.calorieCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz8QsfGuR3EDB8rElpuSIWuJNSJ24gFro',
    appId: '1:303663460854:web:9f7713c5a38b4775f597d7',
    messagingSenderId: '303663460854',
    projectId: 'calorie-calculator-app-2025',
    authDomain: 'calorie-calculator-app-2025.firebaseapp.com',
    storageBucket: 'calorie-calculator-app-2025.firebasestorage.app',
  );
}
